import type { Question } from '../types/test.types';

export const TEST_QUESTIONS: Question[] = [
    {
        id: 'q1_intensity',
        type: 'scale',
        text: '¿Qué tan intensa prefieres la fragancia de tu perfume?',
        options: [
            { value: 1, label: 'Muy sutil' },
            { value: 2, label: 'Ligera' },
            { value: 3, label: 'Moderada' },
            { value: 4, label: 'Intensa' },
            { value: 5, label: 'Muy intensa' },
        ],
        required: true,
    },
    {
        id: 'q2_preferred_families',
        type: 'multiple',
        text: '¿Cuáles de estos aromas te resultan más atractivos? (Máx. 3)',
        options: [
            { value: 'citrus', label: 'Cítricos frescos' },
            { value: 'floral', label: 'Florales románticos' },
            { value: 'woody', label: 'Amaderados elegantes' },
            { value: 'sweet', label: 'Dulces gourmands' },
            { value: 'spicy', label: 'Orientales especiados' },
            { value: 'green', label: 'Verdes naturales' },
            { value: 'aquatic', label: 'Acuáticos marinos' },
        ],
        multiple: true,
        required: true,
    },
    {
        id: 'q3_rejected_families',
        type: 'multiple',
        text: '¿Hay algún tipo de aroma que definitivamente NO te gusta?',
        options: [
            { value: 'citrus', label: 'Cítricos frescos' },
            { value: 'floral', label: 'Florales románticos' },
            { value: 'woody', label: 'Amaderados elegantes' },
            { value: 'sweet', label: 'Dulces gourmands' },
            { value: 'spicy', label: 'Orientales especiados' },
            { value: 'green', label: 'Verdes naturales' },
            { value: 'aquatic', label: 'Acuáticos marinos' },
        ],
        multiple: true,
        required: false,
    },
    {
        id: 'q4_emotion',
        type: 'single',
        text: '¿Qué sensación buscas que transmita tu perfume?',
        options: [
            { value: 'freshness', label: 'Frescura y energía' },
            { value: 'elegance', label: 'Elegancia y sofisticación' },
            { value: 'sensuality', label: 'Sensualidad y calidez' },
            { value: 'calm', label: 'Calma y serenidad' },
            { value: 'joy', label: 'Alegría y optimismo' },
            { value: 'confidence', label: 'Confianza y poder' },
        ],
        required: true,
    },
    {
        id: 'q5_time_of_day',
        type: 'multiple',
        text: '¿Cuándo usarías principalmente este perfume?',
        options: [
            { value: 'morning', label: 'Mañana/día' },
            { value: 'afternoon', label: 'Tarde/atardecer' },
            { value: 'night', label: 'Noche/eventos' },
            { value: 'anytime', label: 'Cualquier momento' },
        ],
        multiple: true,
        required: true,
    },
    {
        id: 'q6_occasions',
        type: 'multiple',
        text: '¿En qué situaciones lo usarías?',
        options: [
            { value: 'work', label: 'Trabajo/oficina' },
            { value: 'daily', label: 'Vida cotidiana' },
            { value: 'special_events', label: 'Eventos especiales' },
            { value: 'romantic', label: 'Citas románticas' },
            { value: 'sports', label: 'Deportes/actividades' },
            { value: 'any', label: 'Cualquier ocasión' },
        ],
        multiple: true,
        required: true,
    },
    {
        id: 'q7_season',
        type: 'single',
        text: '¿En qué estación te imaginas usando este perfume?',
        options: [
            { value: 'spring', label: 'Primavera' },
            { value: 'summer', label: 'Verano' },
            { value: 'autumn', label: 'Otoño' },
            { value: 'winter', label: 'Invierno' },
            { value: 'all_year', label: 'Todo el año' },
        ],
        required: true,
    },
    {
        id: 'q8_longevity',
        type: 'scale',
        text: '¿Cuánto tiempo quieres que dure el aroma en tu piel?',
        options: [
            { value: 1, label: 'Muy corto (1-2h)' },
            { value: 2, label: 'Corto (2-4h)' },
            { value: 3, label: 'Moderado (4-6h)' },
            { value: 4, label: 'Largo (6-8h)' },
            { value: 5, label: 'Muy largo (+8h)' },
        ],
        required: true,
    },
    {
        id: 'q9_concentration',
        type: 'single',
        text: '¿Qué tipo de fragancia prefieres?',
        options: [
            { value: 'eau_de_cologne', label: 'Eau de Cologne' },
            { value: 'eau_de_toilette', label: 'Eau de Toilette' },
            { value: 'eau_de_parfum', label: 'Eau de Parfum' },
            { value: 'parfum', label: 'Parfum' },
            { value: 'not_sure', label: 'No estoy seguro/a' },
        ],
        required: false,
    },
    {
        id: 'q10_reference',
        type: 'text',
        text: 'Si recuerdas algún perfume que te haya gustado mucho, escribe su nombre (opcional)',
        required: false,
    },
];
